// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sen.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sen::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sen::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> sen::ap_ST_fsm_state1 = "1";
const sc_lv<16> sen::ap_ST_fsm_state2 = "10";
const sc_lv<16> sen::ap_ST_fsm_state3 = "100";
const sc_lv<16> sen::ap_ST_fsm_state4 = "1000";
const sc_lv<16> sen::ap_ST_fsm_state5 = "10000";
const sc_lv<16> sen::ap_ST_fsm_state6 = "100000";
const sc_lv<16> sen::ap_ST_fsm_state7 = "1000000";
const sc_lv<16> sen::ap_ST_fsm_state8 = "10000000";
const sc_lv<16> sen::ap_ST_fsm_state9 = "100000000";
const sc_lv<16> sen::ap_ST_fsm_state10 = "1000000000";
const sc_lv<16> sen::ap_ST_fsm_state11 = "10000000000";
const sc_lv<16> sen::ap_ST_fsm_state12 = "100000000000";
const sc_lv<16> sen::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<16> sen::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<16> sen::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<16> sen::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> sen::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> sen::ap_const_lv32_1 = "1";
const sc_lv<32> sen::ap_const_lv32_2 = "10";
const sc_lv<32> sen::ap_const_lv32_6 = "110";
const sc_lv<1> sen::ap_const_lv1_0 = "0";
const sc_lv<32> sen::ap_const_lv32_7 = "111";
const sc_lv<32> sen::ap_const_lv32_8 = "1000";
const sc_lv<32> sen::ap_const_lv32_9 = "1001";
const sc_lv<32> sen::ap_const_lv32_A = "1010";
const sc_lv<32> sen::ap_const_lv32_B = "1011";
const sc_lv<32> sen::ap_const_lv32_C = "1100";
const sc_lv<32> sen::ap_const_lv32_D = "1101";
const sc_lv<32> sen::ap_const_lv32_E = "1110";
const sc_lv<32> sen::ap_const_lv32_1F = "11111";
const sc_lv<32> sen::ap_const_lv32_17 = "10111";
const sc_lv<32> sen::ap_const_lv32_1E = "11110";
const sc_lv<8> sen::ap_const_lv8_7E = "1111110";
const sc_lv<8> sen::ap_const_lv8_C2 = "11000010";
const sc_lv<8> sen::ap_const_lv8_3F = "111111";
const sc_lv<32> sen::ap_const_lv32_4 = "100";
const sc_lv<32> sen::ap_const_lv32_14 = "10100";
const sc_lv<32> sen::ap_const_lv32_63 = "1100011";
const sc_lv<1> sen::ap_const_lv1_1 = "1";
const sc_lv<23> sen::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<32> sen::ap_const_lv32_13 = "10011";
const sc_lv<32> sen::ap_const_lv32_4C = "1001100";
const sc_lv<32> sen::ap_const_lv32_4D = "1001101";
const sc_lv<32> sen::ap_const_lv32_4F = "1001111";
const sc_lv<3> sen::ap_const_lv3_0 = "000";
const sc_lv<58> sen::ap_const_lv58_0 = "0000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> sen::ap_const_lv32_1D = "11101";
const sc_lv<32> sen::ap_const_lv32_39 = "111001";
const sc_lv<2> sen::ap_const_lv2_3 = "11";
const sc_lv<8> sen::ap_const_lv8_83 = "10000011";
const sc_lv<8> sen::ap_const_lv8_0 = "00000000";
const sc_lv<9> sen::ap_const_lv9_0 = "000000000";
const sc_lv<8> sen::ap_const_lv8_FF = "11111111";
const sc_lv<32> sen::ap_const_lv32_16 = "10110";
const sc_lv<32> sen::ap_const_lv32_1C = "11100";
const sc_lv<32> sen::ap_const_lv32_15 = "10101";
const sc_lv<32> sen::ap_const_lv32_F = "1111";
const sc_lv<32> sen::ap_const_lv32_2C = "101100";
const sc_lv<32> sen::ap_const_lv32_10 = "10000";
const sc_lv<29> sen::ap_const_lv29_1FFFFFFF = "11111111111111111111111111111";
const sc_lv<23> sen::ap_const_lv23_7FFFFF = "11111111111111111111111";
const bool sen::ap_const_boolean_1 = true;

sen::sen(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ref_4oPi_table_100_V_U = new sen_ref_4oPi_tablbkb("ref_4oPi_table_100_V_U");
    ref_4oPi_table_100_V_U->clk(ap_clk);
    ref_4oPi_table_100_V_U->reset(ap_rst);
    ref_4oPi_table_100_V_U->address0(ref_4oPi_table_100_V_address0);
    ref_4oPi_table_100_V_U->ce0(ref_4oPi_table_100_V_ce0);
    ref_4oPi_table_100_V_U->q0(ref_4oPi_table_100_V_q0);
    second_order_float_2_U = new sen_second_order_cud("second_order_float_2_U");
    second_order_float_2_U->clk(ap_clk);
    second_order_float_2_U->reset(ap_rst);
    second_order_float_2_U->address0(second_order_float_2_address0);
    second_order_float_2_U->ce0(second_order_float_2_ce0);
    second_order_float_2_U->q0(second_order_float_2_q0);
    second_order_float_3_U = new sen_second_order_dEe("second_order_float_3_U");
    second_order_float_3_U->clk(ap_clk);
    second_order_float_3_U->reset(ap_rst);
    second_order_float_3_U->address0(second_order_float_3_address0);
    second_order_float_3_U->ce0(second_order_float_3_ce0);
    second_order_float_3_U->q0(second_order_float_3_q0);
    second_order_float_s_U = new sen_second_order_eOg("second_order_float_s_U");
    second_order_float_s_U->clk(ap_clk);
    second_order_float_s_U->reset(ap_rst);
    second_order_float_s_U->address0(second_order_float_s_address0);
    second_order_float_s_U->ce0(second_order_float_s_ce0);
    second_order_float_s_U->q0(second_order_float_s_q0);
    grp_scaled_fixed2ieee_fu_214 = new scaled_fixed2ieee("grp_scaled_fixed2ieee_fu_214");
    grp_scaled_fixed2ieee_fu_214->ap_clk(ap_clk);
    grp_scaled_fixed2ieee_fu_214->ap_rst(ap_rst);
    grp_scaled_fixed2ieee_fu_214->ap_start(grp_scaled_fixed2ieee_fu_214_ap_start);
    grp_scaled_fixed2ieee_fu_214->ap_done(grp_scaled_fixed2ieee_fu_214_ap_done);
    grp_scaled_fixed2ieee_fu_214->ap_idle(grp_scaled_fixed2ieee_fu_214_ap_idle);
    grp_scaled_fixed2ieee_fu_214->ap_ready(grp_scaled_fixed2ieee_fu_214_ap_ready);
    grp_scaled_fixed2ieee_fu_214->in_V(result_V_reg_1127);
    grp_scaled_fixed2ieee_fu_214->prescale(ret_V_2_reg_1132);
    grp_scaled_fixed2ieee_fu_214->ap_return(grp_scaled_fixed2ieee_fu_214_ap_return);
    sen_mul_80ns_24nsfYi_U3 = new sen_mul_80ns_24nsfYi<1,5,80,24,104>("sen_mul_80ns_24nsfYi_U3");
    sen_mul_80ns_24nsfYi_U3->clk(ap_clk);
    sen_mul_80ns_24nsfYi_U3->reset(ap_rst);
    sen_mul_80ns_24nsfYi_U3->din0(grp_fu_318_p0);
    sen_mul_80ns_24nsfYi_U3->din1(grp_fu_318_p1);
    sen_mul_80ns_24nsfYi_U3->ce(ap_var_for_const0);
    sen_mul_80ns_24nsfYi_U3->dout(grp_fu_318_p2);
    sen_mux_83_1_1_1_U4 = new sen_mux_83_1_1_1<1,1,1,1,1,1,1,1,1,1,3,1>("sen_mux_83_1_1_1_U4");
    sen_mux_83_1_1_1_U4->din0(ap_var_for_const1);
    sen_mux_83_1_1_1_U4->din1(ap_var_for_const2);
    sen_mux_83_1_1_1_U4->din2(ap_var_for_const2);
    sen_mux_83_1_1_1_U4->din3(ap_var_for_const1);
    sen_mux_83_1_1_1_U4->din4(ap_var_for_const1);
    sen_mux_83_1_1_1_U4->din5(ap_var_for_const2);
    sen_mux_83_1_1_1_U4->din6(ap_var_for_const2);
    sen_mux_83_1_1_1_U4->din7(ap_var_for_const1);
    sen_mux_83_1_1_1_U4->din8(p_Val2_25_reg_1002);
    sen_mux_83_1_1_1_U4->dout(cos_basis_fu_525_p10);
    sen_mux_164_1_1_1_U5 = new sen_mux_164_1_1_1<1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1>("sen_mux_164_1_1_1_U5");
    sen_mux_164_1_1_1_U5->din0(ap_var_for_const1);
    sen_mux_164_1_1_1_U5->din1(ap_var_for_const1);
    sen_mux_164_1_1_1_U5->din2(ap_var_for_const1);
    sen_mux_164_1_1_1_U5->din3(ap_var_for_const2);
    sen_mux_164_1_1_1_U5->din4(ap_var_for_const2);
    sen_mux_164_1_1_1_U5->din5(ap_var_for_const2);
    sen_mux_164_1_1_1_U5->din6(ap_var_for_const2);
    sen_mux_164_1_1_1_U5->din7(ap_var_for_const1);
    sen_mux_164_1_1_1_U5->din8(ap_var_for_const1);
    sen_mux_164_1_1_1_U5->din9(ap_var_for_const2);
    sen_mux_164_1_1_1_U5->din10(ap_var_for_const2);
    sen_mux_164_1_1_1_U5->din11(ap_var_for_const2);
    sen_mux_164_1_1_1_U5->din12(ap_var_for_const2);
    sen_mux_164_1_1_1_U5->din13(ap_var_for_const1);
    sen_mux_164_1_1_1_U5->din14(ap_var_for_const1);
    sen_mux_164_1_1_1_U5->din15(ap_var_for_const1);
    sen_mux_164_1_1_1_U5->din16(p_Result_20_fu_742_p3);
    sen_mux_164_1_1_1_U5->dout(tmp_fu_748_p18);
    sen_mux_164_1_1_1_U6 = new sen_mux_164_1_1_1<1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1>("sen_mux_164_1_1_1_U6");
    sen_mux_164_1_1_1_U6->din0(ap_var_for_const1);
    sen_mux_164_1_1_1_U6->din1(ap_var_for_const1);
    sen_mux_164_1_1_1_U6->din2(ap_var_for_const2);
    sen_mux_164_1_1_1_U6->din3(ap_var_for_const1);
    sen_mux_164_1_1_1_U6->din4(ap_var_for_const2);
    sen_mux_164_1_1_1_U6->din5(ap_var_for_const2);
    sen_mux_164_1_1_1_U6->din6(ap_var_for_const1);
    sen_mux_164_1_1_1_U6->din7(ap_var_for_const2);
    sen_mux_164_1_1_1_U6->din8(ap_var_for_const2);
    sen_mux_164_1_1_1_U6->din9(ap_var_for_const1);
    sen_mux_164_1_1_1_U6->din10(ap_var_for_const2);
    sen_mux_164_1_1_1_U6->din11(ap_var_for_const2);
    sen_mux_164_1_1_1_U6->din12(ap_var_for_const1);
    sen_mux_164_1_1_1_U6->din13(ap_var_for_const2);
    sen_mux_164_1_1_1_U6->din14(ap_var_for_const1);
    sen_mux_164_1_1_1_U6->din15(ap_var_for_const1);
    sen_mux_164_1_1_1_U6->din16(p_Result_20_fu_742_p3);
    sen_mux_164_1_1_1_U6->dout(tmp_1_fu_786_p18);
    sen_mul_mul_15ns_g8j_U7 = new sen_mul_mul_15ns_g8j<1,1,15,15,30>("sen_mul_mul_15ns_g8j_U7");
    sen_mul_mul_15ns_g8j_U7->din0(r_V_11_fu_921_p0);
    sen_mul_mul_15ns_g8j_U7->din1(r_V_11_fu_921_p1);
    sen_mul_mul_15ns_g8j_U7->dout(r_V_11_fu_921_p2);
    sen_mul_mul_15ns_hbi_U8 = new sen_mul_mul_15ns_hbi<1,1,15,15,30>("sen_mul_mul_15ns_hbi_U8");
    sen_mul_mul_15ns_hbi_U8->din0(r_V_13_fu_928_p0);
    sen_mul_mul_15ns_hbi_U8->din1(second_order_float_8_reg_1102);
    sen_mul_mul_15ns_hbi_U8->dout(r_V_13_fu_928_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_B_V_fu_556_p1);
    sensitive << ( p_0237_0_in_i_i_fu_518_p3 );

    SC_METHOD(thread_Ex_V_fu_452_p2);
    sensitive << ( storemerge_i_i_fu_424_p3 );
    sensitive << ( tmp_18_i_i_fu_449_p1 );

    SC_METHOD(thread_Mx_V_read_assign_fu_650_p3);
    sensitive << ( Mx_V_reg_1019 );
    sensitive << ( cos_basis_reg_1055 );

    SC_METHOD(thread_Mx_bits_V_1_fu_359_p2);
    sensitive << ( p_Val2_24_reg_991 );

    SC_METHOD(thread_Mx_zeros_V_fu_415_p1);
    sensitive << ( val_assign_fu_407_p3 );

    SC_METHOD(thread_addr_V_fu_258_p3);
    sensitive << ( closepath_fu_246_p2 );
    sensitive << ( expv_op_i_i_fu_252_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( p_Result_21_fu_907_p4 );

    SC_METHOD(thread_closepath_fu_246_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_V_fu_232_p4 );

    SC_METHOD(thread_expv_op_i_i_fu_252_p2);
    sensitive << ( tmp_V_fu_232_p4 );

    SC_METHOD(thread_grp_fu_318_p0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fu_318_p00 );

    SC_METHOD(thread_grp_fu_318_p00);
    sensitive << ( Med_V_reg_970 );

    SC_METHOD(thread_grp_fu_318_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fu_318_p10 );

    SC_METHOD(thread_grp_fu_318_p10);
    sensitive << ( p_Result_15_fu_304_p3 );

    SC_METHOD(thread_grp_scaled_fixed2ieee_fu_214_ap_start);
    sensitive << ( grp_scaled_fixed2ieee_fu_214_ap_start_reg );

    SC_METHOD(thread_isNeg_fu_462_p3);
    sensitive << ( Ex_V_fu_452_p2 );

    SC_METHOD(thread_lhs_V_1_fu_656_p1);
    sensitive << ( t1_V_reg_1092 );

    SC_METHOD(thread_not_or_cond_i_demorg_fu_860_p2);
    sensitive << ( tmp_28_i_reg_985 );
    sensitive << ( tmp_27_i_reg_1042 );

    SC_METHOD(thread_not_or_cond_i_fu_864_p2);
    sensitive << ( not_or_cond_i_demorg_fu_860_p2 );

    SC_METHOD(thread_not_tmp_i_fu_835_p2);
    sensitive << ( tmp_29_i_reg_1048 );

    SC_METHOD(thread_or_cond_i_fu_831_p2);
    sensitive << ( tmp_28_i_reg_985 );
    sensitive << ( tmp_27_i_reg_1042 );

    SC_METHOD(thread_p_0237_0_in_i_i_fu_518_p3);
    sensitive << ( isNeg_reg_1031 );
    sensitive << ( tmp_24_i_i_fu_508_p1 );
    sensitive << ( tmp_25_i_i_fu_512_p2 );

    SC_METHOD(thread_p_1_i_i_fu_419_p2);
    sensitive << ( tmp_V_reg_941 );

    SC_METHOD(thread_p_Ex_V_ret_i_fu_677_p3);
    sensitive << ( Ex_V_reg_1026 );
    sensitive << ( cos_basis_reg_1055 );

    SC_METHOD(thread_p_Repl2_3_fu_853_p3);
    sensitive << ( results_sign_V_1_reg_935 );
    sensitive << ( or_cond_i_fu_831_p2 );
    sensitive << ( p_Repl2_9_trunc_s_fu_845_p3 );

    SC_METHOD(thread_p_Repl2_9_trunc_s_fu_845_p3);
    sensitive << ( tmp_11_i_fu_840_p2 );
    sensitive << ( not_tmp_i_fu_835_p2 );
    sensitive << ( p_Result_19_fu_720_p3 );

    SC_METHOD(thread_p_Result_15_fu_304_p3);
    sensitive << ( tmp_V_1_reg_948 );

    SC_METHOD(thread_p_Result_16_fu_381_p3);
    sensitive << ( p_Result_i_i_i_fu_371_p4 );

    SC_METHOD(thread_p_Result_17_fu_399_p3);
    sensitive << ( p_Result_s_fu_389_p4 );

    SC_METHOD(thread_p_Result_18_fu_576_p3);
    sensitive << ( sin_basis_fu_570_p2 );
    sensitive << ( p_Result_i_i_fu_546_p4 );

    SC_METHOD(thread_p_Result_19_fu_720_p3);
    sensitive << ( p_Val2_20_fu_717_p1 );

    SC_METHOD(thread_p_Result_1_i_cast_fu_891_p3);
    sensitive << ( not_or_cond_i_fu_864_p2 );

    SC_METHOD(thread_p_Result_20_fu_742_p3);
    sensitive << ( results_sign_V_1_reg_935 );
    sensitive << ( p_Val2_25_reg_1002 );

    SC_METHOD(thread_p_Result_21_fu_907_p4);
    sensitive << ( p_Repl2_3_fu_853_p3 );
    sensitive << ( ret_V_8_fu_883_p3 );
    sensitive << ( ret_V_9_fu_899_p3 );

    SC_METHOD(thread_p_Result_i_cast_fu_870_p3);
    sensitive << ( not_or_cond_i_fu_864_p2 );

    SC_METHOD(thread_p_Result_i_i_fu_546_p4);
    sensitive << ( p_0237_0_in_i_i_fu_518_p3 );

    SC_METHOD(thread_p_Result_i_i_i_fu_371_p4);
    sensitive << ( p_Val2_7_fu_364_p3 );

    SC_METHOD(thread_p_Result_s_fu_389_p4);
    sensitive << ( p_Result_16_fu_381_p3 );

    SC_METHOD(thread_p_Val2_20_fu_717_p1);
    sensitive << ( resultf_reg_1137 );

    SC_METHOD(thread_p_Val2_25_fu_349_p3);
    sensitive << ( closepath_reg_954 );
    sensitive << ( tmp_12_i_i_reg_997 );

    SC_METHOD(thread_p_Val2_7_fu_364_p3);
    sensitive << ( p_Val2_24_reg_991 );
    sensitive << ( tmp_7_fu_355_p1 );
    sensitive << ( Mx_bits_V_1_fu_359_p2 );

    SC_METHOD(thread_p_Val2_s_fu_220_p1);
    sensitive << ( Entrada );

    SC_METHOD(thread_r_V_10_fu_434_p2);
    sensitive << ( p_Val2_7_reg_1008 );
    sensitive << ( tmp_15_i_i_fu_431_p1 );

    SC_METHOD(thread_r_V_11_fu_921_p0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( r_V_fu_591_p1 );

    SC_METHOD(thread_r_V_11_fu_921_p1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( r_V_fu_591_p1 );

    SC_METHOD(thread_r_V_12_fu_619_p0);
    sensitive << ( second_order_float_6_reg_1097 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_r_V_12_fu_619_p1);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( r_V_12_fu_619_p10 );

    SC_METHOD(thread_r_V_12_fu_619_p10);
    sensitive << ( B_V_reg_1062 );

    SC_METHOD(thread_r_V_12_fu_619_p2);
    sensitive << ( r_V_12_fu_619_p0 );
    sensitive << ( r_V_12_fu_619_p1 );

    SC_METHOD(thread_r_V_13_fu_928_p0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( r_V_13_fu_928_p00 );

    SC_METHOD(thread_r_V_13_fu_928_p00);
    sensitive << ( B_squared_V_reg_1087 );

    SC_METHOD(thread_r_V_14_fu_689_p0);
    sensitive << ( ret_V_reg_1122 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_r_V_14_fu_689_p1);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( r_V_14_fu_689_p10 );

    SC_METHOD(thread_r_V_14_fu_689_p10);
    sensitive << ( Mx_V_read_assign_reg_1117 );

    SC_METHOD(thread_r_V_14_fu_689_p2);
    sensitive << ( r_V_14_fu_689_p0 );
    sensitive << ( r_V_14_fu_689_p1 );

    SC_METHOD(thread_r_V_9_fu_288_p2);
    sensitive << ( ref_4oPi_table_100_V_q0 );
    sensitive << ( tmp_7_i_i_i_fu_285_p1 );

    SC_METHOD(thread_r_V_fu_591_p1);
    sensitive << ( B_trunc_V_reg_1067 );

    SC_METHOD(thread_ref_4oPi_table_100_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_5_i_i_i_fu_276_p1 );

    SC_METHOD(thread_ref_4oPi_table_100_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ret_V_11_fu_662_p2);
    sensitive << ( lhs_V_1_fu_656_p1 );
    sensitive << ( rhs_V_1_fu_659_p1 );

    SC_METHOD(thread_ret_V_2_fu_710_p2);
    sensitive << ( rhs_V_2_fu_706_p1 );

    SC_METHOD(thread_ret_V_8_fu_883_p3);
    sensitive << ( tmp_2_fu_878_p2 );
    sensitive << ( p_Result_i_cast_fu_870_p3 );
    sensitive << ( tmp_V_2_fu_728_p4 );

    SC_METHOD(thread_ret_V_9_fu_899_p3);
    sensitive << ( tmp_2_fu_878_p2 );
    sensitive << ( p_Result_1_i_cast_fu_891_p3 );
    sensitive << ( tmp_V_3_fu_738_p1 );

    SC_METHOD(thread_ret_V_fu_671_p2);
    sensitive << ( ret_V_11_fu_662_p2 );
    sensitive << ( rhs_V_2_i_cast_fu_668_p1 );

    SC_METHOD(thread_rhs_V_1_fu_659_p1);
    sensitive << ( tmp_7_i_i_reg_1107 );

    SC_METHOD(thread_rhs_V_2_fu_706_p1);
    sensitive << ( p_Ex_V_ret_i_fu_677_p3 );

    SC_METHOD(thread_rhs_V_2_i_cast_fu_668_p1);
    sensitive << ( tmp_9_i_i_reg_1112 );

    SC_METHOD(thread_second_order_float_2_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_26_i_i_fu_584_p1 );

    SC_METHOD(thread_second_order_float_2_ce0);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_second_order_float_3_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_26_i_i_fu_584_p1 );

    SC_METHOD(thread_second_order_float_3_ce0);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_second_order_float_s_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_26_i_i_fu_584_p1 );

    SC_METHOD(thread_second_order_float_s_ce0);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_sh_assign_4_i_i_cast_1_fu_494_p1);
    sensitive << ( ush_reg_1036 );

    SC_METHOD(thread_sh_assign_4_i_i_cast_fu_497_p1);
    sensitive << ( ush_reg_1036 );

    SC_METHOD(thread_sh_i_i_cast_fu_458_p1);
    sensitive << ( Ex_V_fu_452_p2 );

    SC_METHOD(thread_sin_basis_fu_570_p2);
    sensitive << ( cos_basis_fu_525_p10 );

    SC_METHOD(thread_storemerge_i_i_fu_424_p3);
    sensitive << ( closepath_reg_954 );
    sensitive << ( p_1_i_i_fu_419_p2 );

    SC_METHOD(thread_tmp_11_i_fu_840_p2);
    sensitive << ( tmp_29_i_reg_1048 );
    sensitive << ( tmp_26_i_fu_824_p3 );

    SC_METHOD(thread_tmp_15_i_i_fu_431_p1);
    sensitive << ( Mx_zeros_V_reg_1013 );

    SC_METHOD(thread_tmp_18_i_i_fu_449_p1);
    sensitive << ( Mx_zeros_V_reg_1013 );

    SC_METHOD(thread_tmp_20_i_i_fu_470_p2);
    sensitive << ( sh_i_i_cast_fu_458_p1 );

    SC_METHOD(thread_tmp_21_i_i_fu_500_p1);
    sensitive << ( Mx_V_reg_1019 );

    SC_METHOD(thread_tmp_22_i_i_fu_503_p2);
    sensitive << ( Mx_V_reg_1019 );
    sensitive << ( sh_assign_4_i_i_cast_fu_497_p1 );

    SC_METHOD(thread_tmp_24_i_i_fu_508_p1);
    sensitive << ( tmp_22_i_i_fu_503_p2 );

    SC_METHOD(thread_tmp_25_i_i_fu_512_p2);
    sensitive << ( tmp_21_i_i_fu_500_p1 );
    sensitive << ( sh_assign_4_i_i_cast_1_fu_494_p1 );

    SC_METHOD(thread_tmp_26_i_fu_824_p3);
    sensitive << ( cos_basis_reg_1055 );
    sensitive << ( tmp_fu_748_p18 );
    sensitive << ( tmp_1_fu_786_p18 );

    SC_METHOD(thread_tmp_26_i_i_fu_584_p1);
    sensitive << ( p_Result_18_fu_576_p3 );

    SC_METHOD(thread_tmp_27_i_fu_484_p2);
    sensitive << ( tmp_V_reg_941 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_tmp_28_i_fu_324_p2);
    sensitive << ( tmp_V_1_reg_948 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_tmp_29_i_fu_489_p2);
    sensitive << ( tmp_V_reg_941 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_tmp_2_fu_878_p2);
    sensitive << ( tmp_29_i_reg_1048 );
    sensitive << ( or_cond_i_fu_831_p2 );

    SC_METHOD(thread_tmp_3_fu_266_p4);
    sensitive << ( addr_V_fu_258_p3 );

    SC_METHOD(thread_tmp_5_i_i_i_fu_276_p1);
    sensitive << ( tmp_3_fu_266_p4 );

    SC_METHOD(thread_tmp_6_fu_281_p1);
    sensitive << ( addr_V_fu_258_p3 );

    SC_METHOD(thread_tmp_7_fu_355_p1);
    sensitive << ( p_Val2_25_fu_349_p3 );

    SC_METHOD(thread_tmp_7_i_i_i_fu_285_p1);
    sensitive << ( tmp_6_reg_965 );

    SC_METHOD(thread_tmp_V_1_fu_242_p1);
    sensitive << ( p_Val2_s_fu_220_p1 );

    SC_METHOD(thread_tmp_V_2_fu_728_p4);
    sensitive << ( p_Val2_20_fu_717_p1 );

    SC_METHOD(thread_tmp_V_3_fu_738_p1);
    sensitive << ( p_Val2_20_fu_717_p1 );

    SC_METHOD(thread_tmp_V_fu_232_p4);
    sensitive << ( p_Val2_s_fu_220_p1 );

    SC_METHOD(thread_ush_fu_476_p3);
    sensitive << ( isNeg_fu_462_p3 );
    sensitive << ( sh_i_i_cast_fu_458_p1 );
    sensitive << ( tmp_20_i_i_fu_470_p2 );

    SC_METHOD(thread_val_assign_fu_407_p3);
    sensitive << ( p_Result_17_fu_399_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( grp_scaled_fixed2ieee_fu_214_ap_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "0000000000000001";
    grp_scaled_fixed2ieee_fu_214_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sen_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, Entrada, "(port)Entrada");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ref_4oPi_table_100_V_address0, "ref_4oPi_table_100_V_address0");
    sc_trace(mVcdFile, ref_4oPi_table_100_V_ce0, "ref_4oPi_table_100_V_ce0");
    sc_trace(mVcdFile, ref_4oPi_table_100_V_q0, "ref_4oPi_table_100_V_q0");
    sc_trace(mVcdFile, second_order_float_2_address0, "second_order_float_2_address0");
    sc_trace(mVcdFile, second_order_float_2_ce0, "second_order_float_2_ce0");
    sc_trace(mVcdFile, second_order_float_2_q0, "second_order_float_2_q0");
    sc_trace(mVcdFile, second_order_float_3_address0, "second_order_float_3_address0");
    sc_trace(mVcdFile, second_order_float_3_ce0, "second_order_float_3_ce0");
    sc_trace(mVcdFile, second_order_float_3_q0, "second_order_float_3_q0");
    sc_trace(mVcdFile, second_order_float_s_address0, "second_order_float_s_address0");
    sc_trace(mVcdFile, second_order_float_s_ce0, "second_order_float_s_ce0");
    sc_trace(mVcdFile, second_order_float_s_q0, "second_order_float_s_q0");
    sc_trace(mVcdFile, results_sign_V_1_reg_935, "results_sign_V_1_reg_935");
    sc_trace(mVcdFile, tmp_V_fu_232_p4, "tmp_V_fu_232_p4");
    sc_trace(mVcdFile, tmp_V_reg_941, "tmp_V_reg_941");
    sc_trace(mVcdFile, tmp_V_1_fu_242_p1, "tmp_V_1_fu_242_p1");
    sc_trace(mVcdFile, tmp_V_1_reg_948, "tmp_V_1_reg_948");
    sc_trace(mVcdFile, closepath_fu_246_p2, "closepath_fu_246_p2");
    sc_trace(mVcdFile, closepath_reg_954, "closepath_reg_954");
    sc_trace(mVcdFile, tmp_6_fu_281_p1, "tmp_6_fu_281_p1");
    sc_trace(mVcdFile, tmp_6_reg_965, "tmp_6_reg_965");
    sc_trace(mVcdFile, Med_V_reg_970, "Med_V_reg_970");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_28_i_fu_324_p2, "tmp_28_i_fu_324_p2");
    sc_trace(mVcdFile, tmp_28_i_reg_985, "tmp_28_i_reg_985");
    sc_trace(mVcdFile, p_Val2_24_reg_991, "p_Val2_24_reg_991");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_12_i_i_reg_997, "tmp_12_i_i_reg_997");
    sc_trace(mVcdFile, p_Val2_25_fu_349_p3, "p_Val2_25_fu_349_p3");
    sc_trace(mVcdFile, p_Val2_25_reg_1002, "p_Val2_25_reg_1002");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, p_Val2_7_fu_364_p3, "p_Val2_7_fu_364_p3");
    sc_trace(mVcdFile, p_Val2_7_reg_1008, "p_Val2_7_reg_1008");
    sc_trace(mVcdFile, Mx_zeros_V_fu_415_p1, "Mx_zeros_V_fu_415_p1");
    sc_trace(mVcdFile, Mx_zeros_V_reg_1013, "Mx_zeros_V_reg_1013");
    sc_trace(mVcdFile, Mx_V_reg_1019, "Mx_V_reg_1019");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, Ex_V_fu_452_p2, "Ex_V_fu_452_p2");
    sc_trace(mVcdFile, Ex_V_reg_1026, "Ex_V_reg_1026");
    sc_trace(mVcdFile, isNeg_fu_462_p3, "isNeg_fu_462_p3");
    sc_trace(mVcdFile, isNeg_reg_1031, "isNeg_reg_1031");
    sc_trace(mVcdFile, ush_fu_476_p3, "ush_fu_476_p3");
    sc_trace(mVcdFile, ush_reg_1036, "ush_reg_1036");
    sc_trace(mVcdFile, tmp_27_i_fu_484_p2, "tmp_27_i_fu_484_p2");
    sc_trace(mVcdFile, tmp_27_i_reg_1042, "tmp_27_i_reg_1042");
    sc_trace(mVcdFile, tmp_29_i_fu_489_p2, "tmp_29_i_fu_489_p2");
    sc_trace(mVcdFile, tmp_29_i_reg_1048, "tmp_29_i_reg_1048");
    sc_trace(mVcdFile, cos_basis_fu_525_p10, "cos_basis_fu_525_p10");
    sc_trace(mVcdFile, cos_basis_reg_1055, "cos_basis_reg_1055");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, B_V_fu_556_p1, "B_V_fu_556_p1");
    sc_trace(mVcdFile, B_V_reg_1062, "B_V_reg_1062");
    sc_trace(mVcdFile, B_trunc_V_reg_1067, "B_trunc_V_reg_1067");
    sc_trace(mVcdFile, B_squared_V_reg_1087, "B_squared_V_reg_1087");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, t1_V_reg_1092, "t1_V_reg_1092");
    sc_trace(mVcdFile, second_order_float_6_reg_1097, "second_order_float_6_reg_1097");
    sc_trace(mVcdFile, second_order_float_8_reg_1102, "second_order_float_8_reg_1102");
    sc_trace(mVcdFile, tmp_7_i_i_reg_1107, "tmp_7_i_i_reg_1107");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_9_i_i_reg_1112, "tmp_9_i_i_reg_1112");
    sc_trace(mVcdFile, Mx_V_read_assign_fu_650_p3, "Mx_V_read_assign_fu_650_p3");
    sc_trace(mVcdFile, Mx_V_read_assign_reg_1117, "Mx_V_read_assign_reg_1117");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ret_V_fu_671_p2, "ret_V_fu_671_p2");
    sc_trace(mVcdFile, ret_V_reg_1122, "ret_V_reg_1122");
    sc_trace(mVcdFile, result_V_reg_1127, "result_V_reg_1127");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ret_V_2_fu_710_p2, "ret_V_2_fu_710_p2");
    sc_trace(mVcdFile, ret_V_2_reg_1132, "ret_V_2_reg_1132");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_214_ap_return, "grp_scaled_fixed2ieee_fu_214_ap_return");
    sc_trace(mVcdFile, resultf_reg_1137, "resultf_reg_1137");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_214_ap_ready, "grp_scaled_fixed2ieee_fu_214_ap_ready");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_214_ap_done, "grp_scaled_fixed2ieee_fu_214_ap_done");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_214_ap_start, "grp_scaled_fixed2ieee_fu_214_ap_start");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_214_ap_idle, "grp_scaled_fixed2ieee_fu_214_ap_idle");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_214_ap_start_reg, "grp_scaled_fixed2ieee_fu_214_ap_start_reg");
    sc_trace(mVcdFile, tmp_5_i_i_i_fu_276_p1, "tmp_5_i_i_i_fu_276_p1");
    sc_trace(mVcdFile, tmp_26_i_i_fu_584_p1, "tmp_26_i_i_fu_584_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_220_p1, "p_Val2_s_fu_220_p1");
    sc_trace(mVcdFile, expv_op_i_i_fu_252_p2, "expv_op_i_i_fu_252_p2");
    sc_trace(mVcdFile, addr_V_fu_258_p3, "addr_V_fu_258_p3");
    sc_trace(mVcdFile, tmp_3_fu_266_p4, "tmp_3_fu_266_p4");
    sc_trace(mVcdFile, tmp_7_i_i_i_fu_285_p1, "tmp_7_i_i_i_fu_285_p1");
    sc_trace(mVcdFile, r_V_9_fu_288_p2, "r_V_9_fu_288_p2");
    sc_trace(mVcdFile, p_Result_15_fu_304_p3, "p_Result_15_fu_304_p3");
    sc_trace(mVcdFile, grp_fu_318_p0, "grp_fu_318_p0");
    sc_trace(mVcdFile, grp_fu_318_p1, "grp_fu_318_p1");
    sc_trace(mVcdFile, grp_fu_318_p2, "grp_fu_318_p2");
    sc_trace(mVcdFile, tmp_7_fu_355_p1, "tmp_7_fu_355_p1");
    sc_trace(mVcdFile, Mx_bits_V_1_fu_359_p2, "Mx_bits_V_1_fu_359_p2");
    sc_trace(mVcdFile, p_Result_i_i_i_fu_371_p4, "p_Result_i_i_i_fu_371_p4");
    sc_trace(mVcdFile, p_Result_16_fu_381_p3, "p_Result_16_fu_381_p3");
    sc_trace(mVcdFile, p_Result_s_fu_389_p4, "p_Result_s_fu_389_p4");
    sc_trace(mVcdFile, p_Result_17_fu_399_p3, "p_Result_17_fu_399_p3");
    sc_trace(mVcdFile, val_assign_fu_407_p3, "val_assign_fu_407_p3");
    sc_trace(mVcdFile, p_1_i_i_fu_419_p2, "p_1_i_i_fu_419_p2");
    sc_trace(mVcdFile, tmp_15_i_i_fu_431_p1, "tmp_15_i_i_fu_431_p1");
    sc_trace(mVcdFile, r_V_10_fu_434_p2, "r_V_10_fu_434_p2");
    sc_trace(mVcdFile, storemerge_i_i_fu_424_p3, "storemerge_i_i_fu_424_p3");
    sc_trace(mVcdFile, tmp_18_i_i_fu_449_p1, "tmp_18_i_i_fu_449_p1");
    sc_trace(mVcdFile, sh_i_i_cast_fu_458_p1, "sh_i_i_cast_fu_458_p1");
    sc_trace(mVcdFile, tmp_20_i_i_fu_470_p2, "tmp_20_i_i_fu_470_p2");
    sc_trace(mVcdFile, sh_assign_4_i_i_cast_fu_497_p1, "sh_assign_4_i_i_cast_fu_497_p1");
    sc_trace(mVcdFile, tmp_22_i_i_fu_503_p2, "tmp_22_i_i_fu_503_p2");
    sc_trace(mVcdFile, tmp_21_i_i_fu_500_p1, "tmp_21_i_i_fu_500_p1");
    sc_trace(mVcdFile, sh_assign_4_i_i_cast_1_fu_494_p1, "sh_assign_4_i_i_cast_1_fu_494_p1");
    sc_trace(mVcdFile, tmp_24_i_i_fu_508_p1, "tmp_24_i_i_fu_508_p1");
    sc_trace(mVcdFile, tmp_25_i_i_fu_512_p2, "tmp_25_i_i_fu_512_p2");
    sc_trace(mVcdFile, p_0237_0_in_i_i_fu_518_p3, "p_0237_0_in_i_i_fu_518_p3");
    sc_trace(mVcdFile, sin_basis_fu_570_p2, "sin_basis_fu_570_p2");
    sc_trace(mVcdFile, p_Result_i_i_fu_546_p4, "p_Result_i_i_fu_546_p4");
    sc_trace(mVcdFile, p_Result_18_fu_576_p3, "p_Result_18_fu_576_p3");
    sc_trace(mVcdFile, r_V_11_fu_921_p2, "r_V_11_fu_921_p2");
    sc_trace(mVcdFile, r_V_12_fu_619_p0, "r_V_12_fu_619_p0");
    sc_trace(mVcdFile, r_V_12_fu_619_p1, "r_V_12_fu_619_p1");
    sc_trace(mVcdFile, r_V_12_fu_619_p2, "r_V_12_fu_619_p2");
    sc_trace(mVcdFile, r_V_13_fu_928_p2, "r_V_13_fu_928_p2");
    sc_trace(mVcdFile, lhs_V_1_fu_656_p1, "lhs_V_1_fu_656_p1");
    sc_trace(mVcdFile, rhs_V_1_fu_659_p1, "rhs_V_1_fu_659_p1");
    sc_trace(mVcdFile, ret_V_11_fu_662_p2, "ret_V_11_fu_662_p2");
    sc_trace(mVcdFile, rhs_V_2_i_cast_fu_668_p1, "rhs_V_2_i_cast_fu_668_p1");
    sc_trace(mVcdFile, r_V_14_fu_689_p0, "r_V_14_fu_689_p0");
    sc_trace(mVcdFile, r_V_14_fu_689_p1, "r_V_14_fu_689_p1");
    sc_trace(mVcdFile, r_V_14_fu_689_p2, "r_V_14_fu_689_p2");
    sc_trace(mVcdFile, p_Ex_V_ret_i_fu_677_p3, "p_Ex_V_ret_i_fu_677_p3");
    sc_trace(mVcdFile, rhs_V_2_fu_706_p1, "rhs_V_2_fu_706_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, p_Val2_20_fu_717_p1, "p_Val2_20_fu_717_p1");
    sc_trace(mVcdFile, p_Result_20_fu_742_p3, "p_Result_20_fu_742_p3");
    sc_trace(mVcdFile, tmp_fu_748_p18, "tmp_fu_748_p18");
    sc_trace(mVcdFile, tmp_1_fu_786_p18, "tmp_1_fu_786_p18");
    sc_trace(mVcdFile, tmp_26_i_fu_824_p3, "tmp_26_i_fu_824_p3");
    sc_trace(mVcdFile, tmp_11_i_fu_840_p2, "tmp_11_i_fu_840_p2");
    sc_trace(mVcdFile, not_tmp_i_fu_835_p2, "not_tmp_i_fu_835_p2");
    sc_trace(mVcdFile, p_Result_19_fu_720_p3, "p_Result_19_fu_720_p3");
    sc_trace(mVcdFile, or_cond_i_fu_831_p2, "or_cond_i_fu_831_p2");
    sc_trace(mVcdFile, p_Repl2_9_trunc_s_fu_845_p3, "p_Repl2_9_trunc_s_fu_845_p3");
    sc_trace(mVcdFile, not_or_cond_i_demorg_fu_860_p2, "not_or_cond_i_demorg_fu_860_p2");
    sc_trace(mVcdFile, not_or_cond_i_fu_864_p2, "not_or_cond_i_fu_864_p2");
    sc_trace(mVcdFile, tmp_2_fu_878_p2, "tmp_2_fu_878_p2");
    sc_trace(mVcdFile, p_Result_i_cast_fu_870_p3, "p_Result_i_cast_fu_870_p3");
    sc_trace(mVcdFile, tmp_V_2_fu_728_p4, "tmp_V_2_fu_728_p4");
    sc_trace(mVcdFile, p_Result_1_i_cast_fu_891_p3, "p_Result_1_i_cast_fu_891_p3");
    sc_trace(mVcdFile, tmp_V_3_fu_738_p1, "tmp_V_3_fu_738_p1");
    sc_trace(mVcdFile, p_Repl2_3_fu_853_p3, "p_Repl2_3_fu_853_p3");
    sc_trace(mVcdFile, ret_V_8_fu_883_p3, "ret_V_8_fu_883_p3");
    sc_trace(mVcdFile, ret_V_9_fu_899_p3, "ret_V_9_fu_899_p3");
    sc_trace(mVcdFile, p_Result_21_fu_907_p4, "p_Result_21_fu_907_p4");
    sc_trace(mVcdFile, r_V_11_fu_921_p0, "r_V_11_fu_921_p0");
    sc_trace(mVcdFile, r_V_fu_591_p1, "r_V_fu_591_p1");
    sc_trace(mVcdFile, r_V_11_fu_921_p1, "r_V_11_fu_921_p1");
    sc_trace(mVcdFile, r_V_13_fu_928_p0, "r_V_13_fu_928_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_318_p00, "grp_fu_318_p00");
    sc_trace(mVcdFile, grp_fu_318_p10, "grp_fu_318_p10");
    sc_trace(mVcdFile, r_V_12_fu_619_p10, "r_V_12_fu_619_p10");
    sc_trace(mVcdFile, r_V_13_fu_928_p00, "r_V_13_fu_928_p00");
    sc_trace(mVcdFile, r_V_14_fu_689_p10, "r_V_14_fu_689_p10");
#endif

    }
    mHdltvinHandle.open("sen.hdltvin.dat");
    mHdltvoutHandle.open("sen.hdltvout.dat");
}

sen::~sen() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete ref_4oPi_table_100_V_U;
    delete second_order_float_2_U;
    delete second_order_float_3_U;
    delete second_order_float_s_U;
    delete grp_scaled_fixed2ieee_fu_214;
    delete sen_mul_80ns_24nsfYi_U3;
    delete sen_mux_83_1_1_1_U4;
    delete sen_mux_164_1_1_1_U5;
    delete sen_mux_164_1_1_1_U6;
    delete sen_mul_mul_15ns_g8j_U7;
    delete sen_mul_mul_15ns_hbi_U8;
}

void sen::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void sen::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv1_0;
}

void sen::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv1_1;
}

void sen::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_scaled_fixed2ieee_fu_214_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
            grp_scaled_fixed2ieee_fu_214_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_scaled_fixed2ieee_fu_214_ap_ready.read())) {
            grp_scaled_fixed2ieee_fu_214_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        B_V_reg_1062 = B_V_fu_556_p1.read();
        B_trunc_V_reg_1067 = p_0237_0_in_i_i_fu_518_p3.read().range(21, 7);
        cos_basis_reg_1055 = cos_basis_fu_525_p10.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        B_squared_V_reg_1087 = r_V_11_fu_921_p2.read().range(29, 15);
        second_order_float_6_reg_1097 = second_order_float_3_q0.read();
        second_order_float_8_reg_1102 = second_order_float_s_q0.read();
        t1_V_reg_1092 = second_order_float_2_q0.read().range(29, 1);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        Ex_V_reg_1026 = Ex_V_fu_452_p2.read();
        Mx_V_reg_1019 = r_V_10_fu_434_p2.read().range(57, 29);
        isNeg_reg_1031 = Ex_V_fu_452_p2.read().range(7, 7);
        tmp_27_i_reg_1042 = tmp_27_i_fu_484_p2.read();
        tmp_29_i_reg_1048 = tmp_29_i_fu_489_p2.read();
        ush_reg_1036 = ush_fu_476_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        Med_V_reg_970 = r_V_9_fu_288_p2.read().range(99, 20);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        Mx_V_read_assign_reg_1117 = Mx_V_read_assign_fu_650_p3.read();
        ret_V_reg_1122 = ret_V_fu_671_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        Mx_zeros_V_reg_1013 = Mx_zeros_V_fu_415_p1.read();
        p_Val2_25_reg_1002 = p_Val2_25_fu_349_p3.read();
        p_Val2_7_reg_1008 = p_Val2_7_fu_364_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        closepath_reg_954 = closepath_fu_246_p2.read();
        results_sign_V_1_reg_935 = p_Val2_s_fu_220_p1.read().range(31, 31);
        tmp_6_reg_965 = tmp_6_fu_281_p1.read();
        tmp_V_1_reg_948 = tmp_V_1_fu_242_p1.read();
        tmp_V_reg_941 = p_Val2_s_fu_220_p1.read().range(30, 23);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        p_Val2_24_reg_991 = grp_fu_318_p2.read().range(76, 19);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        result_V_reg_1127 = r_V_14_fu_689_p2.read().range(57, 29);
        ret_V_2_reg_1132 = ret_V_2_fu_710_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_214_ap_done.read(), ap_const_logic_1))) {
        resultf_reg_1137 = grp_scaled_fixed2ieee_fu_214_ap_return.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(closepath_reg_954.read(), ap_const_lv1_0))) {
        tmp_12_i_i_reg_997 = grp_fu_318_p2.read().range(79, 77);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        tmp_28_i_reg_985 = tmp_28_i_fu_324_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        tmp_7_i_i_reg_1107 = r_V_12_fu_619_p2.read().range(44, 23);
        tmp_9_i_i_reg_1112 = r_V_13_fu_928_p2.read().range(29, 16);
    }
}

void sen::thread_B_V_fu_556_p1() {
    B_V_fu_556_p1 = p_0237_0_in_i_i_fu_518_p3.read().range(22-1, 0);
}

void sen::thread_Ex_V_fu_452_p2() {
    Ex_V_fu_452_p2 = (!storemerge_i_i_fu_424_p3.read().is_01() || !tmp_18_i_i_fu_449_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(storemerge_i_i_fu_424_p3.read()) - sc_biguint<8>(tmp_18_i_i_fu_449_p1.read()));
}

void sen::thread_Mx_V_read_assign_fu_650_p3() {
    Mx_V_read_assign_fu_650_p3 = (!cos_basis_reg_1055.read()[0].is_01())? sc_lv<29>(): ((cos_basis_reg_1055.read()[0].to_bool())? ap_const_lv29_1FFFFFFF: Mx_V_reg_1019.read());
}

void sen::thread_Mx_bits_V_1_fu_359_p2() {
    Mx_bits_V_1_fu_359_p2 = (!ap_const_lv58_0.is_01() || !p_Val2_24_reg_991.read().is_01())? sc_lv<58>(): (sc_biguint<58>(ap_const_lv58_0) - sc_biguint<58>(p_Val2_24_reg_991.read()));
}

void sen::thread_Mx_zeros_V_fu_415_p1() {
    Mx_zeros_V_fu_415_p1 = val_assign_fu_407_p3.read().range(5-1, 0);
}

void sen::thread_addr_V_fu_258_p3() {
    addr_V_fu_258_p3 = (!closepath_fu_246_p2.read()[0].is_01())? sc_lv<8>(): ((closepath_fu_246_p2.read()[0].to_bool())? ap_const_lv8_3F: expv_op_i_i_fu_252_p2.read());
}

void sen::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void sen::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void sen::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void sen::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void sen::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void sen::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void sen::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void sen::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void sen::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void sen::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void sen::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void sen::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void sen::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void sen::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void sen::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sen::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sen::thread_ap_return() {
    ap_return = p_Result_21_fu_907_p4.read();
}

void sen::thread_closepath_fu_246_p2() {
    closepath_fu_246_p2 = (!tmp_V_fu_232_p4.read().is_01() || !ap_const_lv8_7E.is_01())? sc_lv<1>(): (sc_biguint<8>(tmp_V_fu_232_p4.read()) < sc_biguint<8>(ap_const_lv8_7E));
}

void sen::thread_expv_op_i_i_fu_252_p2() {
    expv_op_i_i_fu_252_p2 = (!ap_const_lv8_C2.is_01() || !tmp_V_fu_232_p4.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_C2) + sc_biguint<8>(tmp_V_fu_232_p4.read()));
}

void sen::thread_grp_fu_318_p0() {
    grp_fu_318_p0 =  (sc_lv<80>) (grp_fu_318_p00.read());
}

void sen::thread_grp_fu_318_p00() {
    grp_fu_318_p00 = esl_zext<104,80>(Med_V_reg_970.read());
}

void sen::thread_grp_fu_318_p1() {
    grp_fu_318_p1 =  (sc_lv<24>) (grp_fu_318_p10.read());
}

void sen::thread_grp_fu_318_p10() {
    grp_fu_318_p10 = esl_zext<104,24>(p_Result_15_fu_304_p3.read());
}

void sen::thread_grp_scaled_fixed2ieee_fu_214_ap_start() {
    grp_scaled_fixed2ieee_fu_214_ap_start = grp_scaled_fixed2ieee_fu_214_ap_start_reg.read();
}

void sen::thread_isNeg_fu_462_p3() {
    isNeg_fu_462_p3 = Ex_V_fu_452_p2.read().range(7, 7);
}

void sen::thread_lhs_V_1_fu_656_p1() {
    lhs_V_1_fu_656_p1 = esl_sext<30,29>(t1_V_reg_1092.read());
}

void sen::thread_not_or_cond_i_demorg_fu_860_p2() {
    not_or_cond_i_demorg_fu_860_p2 = (tmp_27_i_reg_1042.read() & tmp_28_i_reg_985.read());
}

void sen::thread_not_or_cond_i_fu_864_p2() {
    not_or_cond_i_fu_864_p2 = (not_or_cond_i_demorg_fu_860_p2.read() ^ ap_const_lv1_1);
}

void sen::thread_not_tmp_i_fu_835_p2() {
    not_tmp_i_fu_835_p2 = (tmp_29_i_reg_1048.read() ^ ap_const_lv1_1);
}

void sen::thread_or_cond_i_fu_831_p2() {
    or_cond_i_fu_831_p2 = (tmp_27_i_reg_1042.read() & tmp_28_i_reg_985.read());
}

void sen::thread_p_0237_0_in_i_i_fu_518_p3() {
    p_0237_0_in_i_i_fu_518_p3 = (!isNeg_reg_1031.read()[0].is_01())? sc_lv<32>(): ((isNeg_reg_1031.read()[0].to_bool())? tmp_24_i_i_fu_508_p1.read(): tmp_25_i_i_fu_512_p2.read());
}

void sen::thread_p_1_i_i_fu_419_p2() {
    p_1_i_i_fu_419_p2 = (!ap_const_lv8_83.is_01() || !tmp_V_reg_941.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_83) + sc_biguint<8>(tmp_V_reg_941.read()));
}

void sen::thread_p_Ex_V_ret_i_fu_677_p3() {
    p_Ex_V_ret_i_fu_677_p3 = (!cos_basis_reg_1055.read()[0].is_01())? sc_lv<8>(): ((cos_basis_reg_1055.read()[0].to_bool())? ap_const_lv8_0: Ex_V_reg_1026.read());
}

void sen::thread_p_Repl2_3_fu_853_p3() {
    p_Repl2_3_fu_853_p3 = (!or_cond_i_fu_831_p2.read()[0].is_01())? sc_lv<1>(): ((or_cond_i_fu_831_p2.read()[0].to_bool())? results_sign_V_1_reg_935.read(): p_Repl2_9_trunc_s_fu_845_p3.read());
}

void sen::thread_p_Repl2_9_trunc_s_fu_845_p3() {
    p_Repl2_9_trunc_s_fu_845_p3 = (!tmp_11_i_fu_840_p2.read()[0].is_01())? sc_lv<1>(): ((tmp_11_i_fu_840_p2.read()[0].to_bool())? not_tmp_i_fu_835_p2.read(): p_Result_19_fu_720_p3.read());
}

void sen::thread_p_Result_15_fu_304_p3() {
    p_Result_15_fu_304_p3 = esl_concat<1,23>(ap_const_lv1_1, tmp_V_1_reg_948.read());
}

void sen::thread_p_Result_16_fu_381_p3() {
    p_Result_16_fu_381_p3 = esl_concat<29,1>(p_Result_i_i_i_fu_371_p4.read(), ap_const_lv1_1);
}

void sen::thread_p_Result_17_fu_399_p3() {
    p_Result_17_fu_399_p3 = esl_concat<2,30>(ap_const_lv2_3, p_Result_s_fu_389_p4.read());
}

void sen::thread_p_Result_18_fu_576_p3() {
    p_Result_18_fu_576_p3 = esl_concat<1,7>(sin_basis_fu_570_p2.read(), p_Result_i_i_fu_546_p4.read());
}

void sen::thread_p_Result_19_fu_720_p3() {
    p_Result_19_fu_720_p3 = p_Val2_20_fu_717_p1.read().range(31, 31);
}

void sen::thread_p_Result_1_i_cast_fu_891_p3() {
    p_Result_1_i_cast_fu_891_p3 = (!not_or_cond_i_fu_864_p2.read()[0].is_01())? sc_lv<23>(): ((not_or_cond_i_fu_864_p2.read()[0].to_bool())? ap_const_lv23_7FFFFF: ap_const_lv23_0);
}

void sen::thread_p_Result_20_fu_742_p3() {
    p_Result_20_fu_742_p3 = esl_concat<1,3>(results_sign_V_1_reg_935.read(), p_Val2_25_reg_1002.read());
}

void sen::thread_p_Result_21_fu_907_p4() {
    p_Result_21_fu_907_p4 = esl_concat<9,23>(esl_concat<1,8>(p_Repl2_3_fu_853_p3.read(), ret_V_8_fu_883_p3.read()), ret_V_9_fu_899_p3.read());
}

void sen::thread_p_Result_i_cast_fu_870_p3() {
    p_Result_i_cast_fu_870_p3 = (!not_or_cond_i_fu_864_p2.read()[0].is_01())? sc_lv<8>(): ((not_or_cond_i_fu_864_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void sen::thread_p_Result_i_i_fu_546_p4() {
    p_Result_i_i_fu_546_p4 = p_0237_0_in_i_i_fu_518_p3.read().range(28, 22);
}

void sen::thread_p_Result_i_i_i_fu_371_p4() {
    p_Result_i_i_i_fu_371_p4 = p_Val2_7_fu_364_p3.read().range(57, 29);
}

void sen::thread_p_Result_s_fu_389_p4() {
    p_Result_s_fu_389_p4 = p_Result_16_fu_381_p3.read().range(0, 29);
}

void sen::thread_p_Val2_20_fu_717_p1() {
    p_Val2_20_fu_717_p1 = resultf_reg_1137.read();
}

void sen::thread_p_Val2_25_fu_349_p3() {
    p_Val2_25_fu_349_p3 = (!closepath_reg_954.read()[0].is_01())? sc_lv<3>(): ((closepath_reg_954.read()[0].to_bool())? ap_const_lv3_0: tmp_12_i_i_reg_997.read());
}

void sen::thread_p_Val2_7_fu_364_p3() {
    p_Val2_7_fu_364_p3 = (!tmp_7_fu_355_p1.read()[0].is_01())? sc_lv<58>(): ((tmp_7_fu_355_p1.read()[0].to_bool())? Mx_bits_V_1_fu_359_p2.read(): p_Val2_24_reg_991.read());
}

void sen::thread_p_Val2_s_fu_220_p1() {
    p_Val2_s_fu_220_p1 = Entrada.read();
}

void sen::thread_r_V_10_fu_434_p2() {
    r_V_10_fu_434_p2 = (!tmp_15_i_i_fu_431_p1.read().is_01())? sc_lv<58>(): p_Val2_7_reg_1008.read() << (unsigned short)tmp_15_i_i_fu_431_p1.read().to_uint();
}

void sen::thread_r_V_11_fu_921_p0() {
    r_V_11_fu_921_p0 =  (sc_lv<15>) (r_V_fu_591_p1.read());
}

void sen::thread_r_V_11_fu_921_p1() {
    r_V_11_fu_921_p1 =  (sc_lv<15>) (r_V_fu_591_p1.read());
}

void sen::thread_r_V_12_fu_619_p0() {
    r_V_12_fu_619_p0 = second_order_float_6_reg_1097.read();
}

void sen::thread_r_V_12_fu_619_p1() {
    r_V_12_fu_619_p1 =  (sc_lv<22>) (r_V_12_fu_619_p10.read());
}

void sen::thread_r_V_12_fu_619_p10() {
    r_V_12_fu_619_p10 = esl_zext<45,22>(B_V_reg_1062.read());
}

void sen::thread_r_V_12_fu_619_p2() {
    r_V_12_fu_619_p2 = (!r_V_12_fu_619_p0.read().is_01() || !r_V_12_fu_619_p1.read().is_01())? sc_lv<45>(): sc_bigint<23>(r_V_12_fu_619_p0.read()) * sc_biguint<22>(r_V_12_fu_619_p1.read());
}

void sen::thread_r_V_13_fu_928_p0() {
    r_V_13_fu_928_p0 =  (sc_lv<15>) (r_V_13_fu_928_p00.read());
}

void sen::thread_r_V_13_fu_928_p00() {
    r_V_13_fu_928_p00 = esl_zext<30,15>(B_squared_V_reg_1087.read());
}

void sen::thread_r_V_14_fu_689_p0() {
    r_V_14_fu_689_p0 = ret_V_reg_1122.read();
}

void sen::thread_r_V_14_fu_689_p1() {
    r_V_14_fu_689_p1 =  (sc_lv<29>) (r_V_14_fu_689_p10.read());
}

void sen::thread_r_V_14_fu_689_p10() {
    r_V_14_fu_689_p10 = esl_zext<58,29>(Mx_V_read_assign_reg_1117.read());
}

void sen::thread_r_V_14_fu_689_p2() {
    r_V_14_fu_689_p2 = (!r_V_14_fu_689_p0.read().is_01() || !r_V_14_fu_689_p1.read().is_01())? sc_lv<58>(): sc_bigint<30>(r_V_14_fu_689_p0.read()) * sc_biguint<29>(r_V_14_fu_689_p1.read());
}

void sen::thread_r_V_9_fu_288_p2() {
    r_V_9_fu_288_p2 = (!tmp_7_i_i_i_fu_285_p1.read().is_01())? sc_lv<100>(): ref_4oPi_table_100_V_q0.read() << (unsigned short)tmp_7_i_i_i_fu_285_p1.read().to_uint();
}

void sen::thread_r_V_fu_591_p1() {
    r_V_fu_591_p1 = esl_zext<30,15>(B_trunc_V_reg_1067.read());
}

void sen::thread_ref_4oPi_table_100_V_address0() {
    ref_4oPi_table_100_V_address0 =  (sc_lv<4>) (tmp_5_i_i_i_fu_276_p1.read());
}

void sen::thread_ref_4oPi_table_100_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        ref_4oPi_table_100_V_ce0 = ap_const_logic_1;
    } else {
        ref_4oPi_table_100_V_ce0 = ap_const_logic_0;
    }
}

void sen::thread_ret_V_11_fu_662_p2() {
    ret_V_11_fu_662_p2 = (!lhs_V_1_fu_656_p1.read().is_01() || !rhs_V_1_fu_659_p1.read().is_01())? sc_lv<30>(): (sc_bigint<30>(lhs_V_1_fu_656_p1.read()) + sc_bigint<30>(rhs_V_1_fu_659_p1.read()));
}

void sen::thread_ret_V_2_fu_710_p2() {
    ret_V_2_fu_710_p2 = (!ap_const_lv9_0.is_01() || !rhs_V_2_fu_706_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_bigint<9>(rhs_V_2_fu_706_p1.read()));
}

void sen::thread_ret_V_8_fu_883_p3() {
    ret_V_8_fu_883_p3 = (!tmp_2_fu_878_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_2_fu_878_p2.read()[0].to_bool())? p_Result_i_cast_fu_870_p3.read(): tmp_V_2_fu_728_p4.read());
}

void sen::thread_ret_V_9_fu_899_p3() {
    ret_V_9_fu_899_p3 = (!tmp_2_fu_878_p2.read()[0].is_01())? sc_lv<23>(): ((tmp_2_fu_878_p2.read()[0].to_bool())? p_Result_1_i_cast_fu_891_p3.read(): tmp_V_3_fu_738_p1.read());
}

void sen::thread_ret_V_fu_671_p2() {
    ret_V_fu_671_p2 = (!ret_V_11_fu_662_p2.read().is_01() || !rhs_V_2_i_cast_fu_668_p1.read().is_01())? sc_lv<30>(): (sc_biguint<30>(ret_V_11_fu_662_p2.read()) + sc_bigint<30>(rhs_V_2_i_cast_fu_668_p1.read()));
}

void sen::thread_rhs_V_1_fu_659_p1() {
    rhs_V_1_fu_659_p1 = esl_sext<30,22>(tmp_7_i_i_reg_1107.read());
}

void sen::thread_rhs_V_2_fu_706_p1() {
    rhs_V_2_fu_706_p1 = esl_sext<9,8>(p_Ex_V_ret_i_fu_677_p3.read());
}

void sen::thread_rhs_V_2_i_cast_fu_668_p1() {
    rhs_V_2_i_cast_fu_668_p1 = esl_sext<30,14>(tmp_9_i_i_reg_1112.read());
}

void sen::thread_second_order_float_2_address0() {
    second_order_float_2_address0 =  (sc_lv<8>) (tmp_26_i_i_fu_584_p1.read());
}

void sen::thread_second_order_float_2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        second_order_float_2_ce0 = ap_const_logic_1;
    } else {
        second_order_float_2_ce0 = ap_const_logic_0;
    }
}

void sen::thread_second_order_float_3_address0() {
    second_order_float_3_address0 =  (sc_lv<8>) (tmp_26_i_i_fu_584_p1.read());
}

void sen::thread_second_order_float_3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        second_order_float_3_ce0 = ap_const_logic_1;
    } else {
        second_order_float_3_ce0 = ap_const_logic_0;
    }
}

void sen::thread_second_order_float_s_address0() {
    second_order_float_s_address0 =  (sc_lv<8>) (tmp_26_i_i_fu_584_p1.read());
}

void sen::thread_second_order_float_s_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        second_order_float_s_ce0 = ap_const_logic_1;
    } else {
        second_order_float_s_ce0 = ap_const_logic_0;
    }
}

void sen::thread_sh_assign_4_i_i_cast_1_fu_494_p1() {
    sh_assign_4_i_i_cast_1_fu_494_p1 = esl_sext<32,9>(ush_reg_1036.read());
}

void sen::thread_sh_assign_4_i_i_cast_fu_497_p1() {
    sh_assign_4_i_i_cast_fu_497_p1 = esl_sext<29,9>(ush_reg_1036.read());
}

void sen::thread_sh_i_i_cast_fu_458_p1() {
    sh_i_i_cast_fu_458_p1 = esl_sext<9,8>(Ex_V_fu_452_p2.read());
}

void sen::thread_sin_basis_fu_570_p2() {
    sin_basis_fu_570_p2 = (cos_basis_fu_525_p10.read() ^ ap_const_lv1_1);
}

void sen::thread_storemerge_i_i_fu_424_p3() {
    storemerge_i_i_fu_424_p3 = (!closepath_reg_954.read()[0].is_01())? sc_lv<8>(): ((closepath_reg_954.read()[0].to_bool())? p_1_i_i_fu_419_p2.read(): ap_const_lv8_0);
}

void sen::thread_tmp_11_i_fu_840_p2() {
    tmp_11_i_fu_840_p2 = (tmp_29_i_reg_1048.read() | tmp_26_i_fu_824_p3.read());
}

void sen::thread_tmp_15_i_i_fu_431_p1() {
    tmp_15_i_i_fu_431_p1 = esl_zext<58,5>(Mx_zeros_V_reg_1013.read());
}

void sen::thread_tmp_18_i_i_fu_449_p1() {
    tmp_18_i_i_fu_449_p1 = esl_zext<8,5>(Mx_zeros_V_reg_1013.read());
}

void sen::thread_tmp_20_i_i_fu_470_p2() {
    tmp_20_i_i_fu_470_p2 = (!ap_const_lv9_0.is_01() || !sh_i_i_cast_fu_458_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_bigint<9>(sh_i_i_cast_fu_458_p1.read()));
}

void sen::thread_tmp_21_i_i_fu_500_p1() {
    tmp_21_i_i_fu_500_p1 = esl_zext<32,29>(Mx_V_reg_1019.read());
}

void sen::thread_tmp_22_i_i_fu_503_p2() {
    tmp_22_i_i_fu_503_p2 = (!sh_assign_4_i_i_cast_fu_497_p1.read().is_01())? sc_lv<29>(): Mx_V_reg_1019.read() >> (unsigned short)sh_assign_4_i_i_cast_fu_497_p1.read().to_uint();
}

void sen::thread_tmp_24_i_i_fu_508_p1() {
    tmp_24_i_i_fu_508_p1 = esl_zext<32,29>(tmp_22_i_i_fu_503_p2.read());
}

void sen::thread_tmp_25_i_i_fu_512_p2() {
    tmp_25_i_i_fu_512_p2 = (!sh_assign_4_i_i_cast_1_fu_494_p1.read().is_01())? sc_lv<32>(): tmp_21_i_i_fu_500_p1.read() << (unsigned short)sh_assign_4_i_i_cast_1_fu_494_p1.read().to_uint();
}

void sen::thread_tmp_26_i_fu_824_p3() {
    tmp_26_i_fu_824_p3 = (!cos_basis_reg_1055.read()[0].is_01())? sc_lv<1>(): ((cos_basis_reg_1055.read()[0].to_bool())? tmp_fu_748_p18.read(): tmp_1_fu_786_p18.read());
}

void sen::thread_tmp_26_i_i_fu_584_p1() {
    tmp_26_i_i_fu_584_p1 = esl_zext<64,8>(p_Result_18_fu_576_p3.read());
}

void sen::thread_tmp_27_i_fu_484_p2() {
    tmp_27_i_fu_484_p2 = (!tmp_V_reg_941.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_reg_941.read() == ap_const_lv8_0);
}

void sen::thread_tmp_28_i_fu_324_p2() {
    tmp_28_i_fu_324_p2 = (!tmp_V_1_reg_948.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_1_reg_948.read() == ap_const_lv23_0);
}

void sen::thread_tmp_29_i_fu_489_p2() {
    tmp_29_i_fu_489_p2 = (!tmp_V_reg_941.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_reg_941.read() == ap_const_lv8_FF);
}

void sen::thread_tmp_2_fu_878_p2() {
    tmp_2_fu_878_p2 = (or_cond_i_fu_831_p2.read() | tmp_29_i_reg_1048.read());
}

void sen::thread_tmp_3_fu_266_p4() {
    tmp_3_fu_266_p4 = addr_V_fu_258_p3.read().range(7, 4);
}

void sen::thread_tmp_5_i_i_i_fu_276_p1() {
    tmp_5_i_i_i_fu_276_p1 = esl_zext<64,4>(tmp_3_fu_266_p4.read());
}

void sen::thread_tmp_6_fu_281_p1() {
    tmp_6_fu_281_p1 = addr_V_fu_258_p3.read().range(4-1, 0);
}

void sen::thread_tmp_7_fu_355_p1() {
    tmp_7_fu_355_p1 = p_Val2_25_fu_349_p3.read().range(1-1, 0);
}

void sen::thread_tmp_7_i_i_i_fu_285_p1() {
    tmp_7_i_i_i_fu_285_p1 = esl_zext<100,4>(tmp_6_reg_965.read());
}

void sen::thread_tmp_V_1_fu_242_p1() {
    tmp_V_1_fu_242_p1 = p_Val2_s_fu_220_p1.read().range(23-1, 0);
}

void sen::thread_tmp_V_2_fu_728_p4() {
    tmp_V_2_fu_728_p4 = p_Val2_20_fu_717_p1.read().range(30, 23);
}

void sen::thread_tmp_V_3_fu_738_p1() {
    tmp_V_3_fu_738_p1 = p_Val2_20_fu_717_p1.read().range(23-1, 0);
}

void sen::thread_tmp_V_fu_232_p4() {
    tmp_V_fu_232_p4 = p_Val2_s_fu_220_p1.read().range(30, 23);
}

void sen::thread_ush_fu_476_p3() {
    ush_fu_476_p3 = (!isNeg_fu_462_p3.read()[0].is_01())? sc_lv<9>(): ((isNeg_fu_462_p3.read()[0].to_bool())? tmp_20_i_i_fu_470_p2.read(): sh_i_i_cast_fu_458_p1.read());
}

void sen::thread_val_assign_fu_407_p3() {
    val_assign_fu_407_p3 = esl_cttz<32,32>(p_Result_17_fu_399_p3.read());
}

void sen::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_214_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state16;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXX";
            break;
    }
}

void sen::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Entrada\" :  \"" << Entrada.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

